### ISSUE TITLE
Internet Explorer does not display margins left and right to the page.

### ISSUE THREAD

**Issue by marcaltmann** [fairmondo/fairmondo#1432] opened 2015-10-05 10:30 UTC
This seems to affect Internet Explorer 11, also. Need to make screenshot and post it here.

**Comment by tomwor** [comment] 2015-11-26 09:55
Issue confirmed on IE11, seems to be a missing max-width statement for the content block.

![fairmondo_ie11_maxwidth](https://cloud.githubusercontent.com/assets/9846466/11420099/12ec5734-942c-11e5-8db3-2c48f501b331.jpg)

**Comment by tomwor** [comment] 2015-11-29 21:03
IE doesn't recognize <main> as a block level element, needs explicit {display:block;} directive.
Fixed in PR https://github.com/fairmondo/fairmondo/pull/1463

**Closed** 2015-11-30 10:34 UTC
Labels: bug, low prio, ready
